"""Interactive setup for the Polymarket BTC bot.

Walks the user through creating a valid .env file. Only asks for
PRIVATE_KEY and FUNDER_ADDRESS — the bot auto-detects signature type.

Run via ./start.sh (auto-invoked when .env is missing) or directly:

    python setup.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from eth_account import Account

ENV_PATH = Path(__file__).resolve().parent / ".env"


def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    label = f"{prompt}"
    if default:
        label += f" [{default}]"
    label += ": "
    if secret:
        import getpass
        val = getpass.getpass(label).strip()
    else:
        val = input(label).strip()
    return val or default


def ask_yes_no(prompt: str, default: bool = True) -> bool:
    suffix = " (Y/n)" if default else " (y/N)"
    ans = input(prompt + suffix + ": ").strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes")


def header(text: str) -> None:
    print()
    print("=" * 60)
    print(f"  {text}")
    print("=" * 60)


def main() -> int:
    header("Polymarket BTC Bot -- Setup")
    print("""
  This creates your .env file. You need TWO things:

    1. Your wallet PRIVATE KEY
    2. Your wallet DEPOSIT ADDRESS (funder)

  The bot auto-detects everything else.
  Press Ctrl+C at any time to abort.
""")

    if ENV_PATH.exists():
        if not ask_yes_no(
            f"  .env already exists. Overwrite?", default=False,
        ):
            print("  Aborted.")
            return 1

    # ── Private key ─────────────────────────────────────────────────
    header("Step 1: Private Key")
    print("""
  Where to find it:

    polymarket.com -> Profile icon -> Settings
    -> scroll to "Export Private Key" -> enter password -> copy it

    OR if MetaMask: click account -> Account Details -> Export Private Key

  The key is a long hex string. It will NOT show as you type.
""")
    while True:
        pk = ask("  Paste your PRIVATE_KEY", secret=True)
        if not pk:
            print("    Required, try again.")
            continue
        if not pk.startswith("0x"):
            pk = "0x" + pk
        try:
            signer_eoa = Account.from_key(pk).address
        except Exception as e:
            print(f"    Invalid key ({e}). Try again.")
            continue
        break

    print(f"\n    Your signer address: {signer_eoa}")

    # ── Funder address ──────────────────────────────────────────────
    header("Step 2: Deposit Address (Funder)")
    print("""
  Where to find it:

    polymarket.com -> click your Profile icon (top right)
    -> click "Deposit" -> copy the 0x address shown

  It starts with 0x and is 42 characters long.
""")
    while True:
        funder = ask("  Paste your DEPOSIT ADDRESS")
        if not funder:
            print("    Required, try again.")
            continue
        funder = funder.strip()
        if not funder.startswith("0x") or len(funder) != 42:
            print("    Must be 42 characters starting with 0x. Try again.")
            continue
        break

    # ── Trading mode ────────────────────────────────────────────────
    header("Step 3: Trading Mode")
    print("""
    1 = LIVE  (real money)
    2 = DRY   (paper trading, no real money)
""")
    while True:
        mode = ask("  Choose 1 or 2", default="1")
        if mode in ("1", "2"):
            break
        print("    Enter 1 or 2.")
    dry_run = "true" if mode == "2" else "false"

    # ── Write .env ──────────────────────────────────────────────────
    header("Saving .env")

    env_contents = f"""# Generated by setup.py

# Polymarket credentials (leave API fields blank -- bot auto-derives them)
POLYMARKET_API_KEY=
POLYMARKET_API_SECRET=
POLYMARKET_API_PASSPHRASE=

# Your wallet private key
PRIVATE_KEY={pk}

# Your deposit/funder address
POLYMARKET_FUNDER_ADDRESS={funder}

# Signature type -- bot auto-detects, but 1=POLY_PROXY 2=GNOSIS_SAFE
POLYMARKET_SIGNATURE_TYPE=1

# Trading mode
DRY_RUN={dry_run}

# Dashboard
DASHBOARD_ENABLED=true
DASHBOARD_PORT=8787
"""
    ENV_PATH.write_text(env_contents)
    try:
        os.chmod(ENV_PATH, 0o600)
    except Exception:
        pass

    print(f"  Saved to {ENV_PATH}")
    print()
    print(f"  Your signer: {signer_eoa}")
    print(f"  Your funder:  {funder}")
    print(f"  Mode:         {'LIVE' if dry_run == 'false' else 'DRY RUN'}")
    print()
    print("  The bot will auto-detect your wallet type on startup.")
    print()
    input("  Press ENTER to launch the bot...")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n  Aborted.")
        sys.exit(1)
