import logging
import math
from dataclasses import dataclass
from typing import Optional

import config
from market_scanner import MarketInfo
from price_feed import PriceSnapshot, MomentumData

logger = logging.getLogger("polymarket_bot.strategy")


@dataclass
class Signal:
    """A trading signal generated by the strategy."""
    direction: str        # "YES" or "NO"
    confidence: float     # Our estimated probability (0-1)
    market_prob: float    # Market-implied probability
    edge: float           # confidence - market_prob (for chosen direction)
    bet_token_id: str     # Token ID to buy
    bet_size_hint: str    # "low", "medium", "high" confidence tier
    reasoning: str        # Human-readable explanation


class TradingStrategy:
    """
    Tape-following strategy for BTC 5-minute binary markets.

    We do NOT try to predict where BTC is going — we follow the tape.
    In the final minute of a 5-min window the current BTC price
    relative to strike is highly predictive: if BTC is already above
    strike with 30s left, YES almost always wins.

    The job here is to recognise cases where Polymarket's price
    HASN'T fully reflected that reality yet, and take the side the
    tape favours. We never bet against a correctly-priced market.
    """

    # Minimum distance from strike to consider a direction "committed"
    # (in % of BTC price). Inside this band it's a coin flip — we skip.
    COIN_FLIP_BAND_PCT = 0.0004   # 0.04% = ~$30 on $75k BTC

    def analyze(
        self,
        market: MarketInfo,
        price: PriceSnapshot,
        momentum: MomentumData,
        yes_price: float,
        no_price: float,
    ) -> Optional[Signal]:
        """Return a Signal if we see tradeable tape-following edge, else None."""
        seconds_left = market.seconds_until_close
        strike = market.strike_price

        # Timing gates
        if seconds_left > config.ENTRY_SECONDS_BEFORE_CLOSE:
            return None
        if seconds_left < config.LATEST_ENTRY_SECONDS:
            logger.info(f"SKIP {market.slug}: too late ({seconds_left:.0f}s left).")
            return None

        if strike <= 0:
            logger.warning(f"Invalid strike price for market: {market.question}")
            return None

        # Stale / edge-of-book prices -> skip
        if yes_price <= 0.02 or yes_price >= 0.98:
            logger.info(
                f"SKIP {market.slug}: market at extreme (YES={yes_price:.3f})."
            )
            return None

        # ---- The tape ----
        distance_pct = (price.price - strike) / strike

        # Coin-flip zone: BTC is too close to strike for a reliable call.
        if abs(distance_pct) < self.COIN_FLIP_BAND_PCT:
            logger.info(
                f"SKIP {market.slug}: coin-flip zone - BTC ${price.price:,.2f} "
                f"vs strike ${strike:,.2f} ({distance_pct*100:+.3f}%)."
            )
            return None

        # Direction the tape currently favours
        if distance_pct > 0:
            tape_direction = "YES"   # BTC above strike -> UP ticket wins
            take_price = yes_price
            bet_token = market.yes_token_id
        else:
            tape_direction = "NO"    # BTC below strike -> DOWN ticket wins
            take_price = no_price
            bet_token = market.no_token_id

        # Is the tape-direction ticket priced in a zone we'll take?
        if take_price < config.MIN_TAKE_PRICE:
            # Market disagrees with where the tape is - something's off,
            # or there's big momentum against us. Don't fight the market.
            logger.info(
                f"SKIP {market.slug}: tape={tape_direction} but market disagrees "
                f"(take_price={take_price:.3f} < {config.MIN_TAKE_PRICE})."
            )
            return None
        if take_price > config.MAX_TAKE_PRICE:
            # No edge left to capture - risking $X to make pennies.
            logger.info(
                f"SKIP {market.slug}: {tape_direction} already fully priced "
                f"(take_price={take_price:.3f} > {config.MAX_TAKE_PRICE})."
            )
            return None

        # ---- Confidence model ----
        # How committed is the tape? Combine distance + time pressure +
        # momentum alignment into a single probability estimate.
        confidence = self._tape_confidence(
            distance_pct=distance_pct,
            seconds_left=seconds_left,
            momentum=momentum,
            tape_direction=tape_direction,
        )

        # Edge is confidence vs what the market is charging for the ticket
        edge = confidence - take_price

        if edge < config.MIN_EDGE_THRESHOLD:
            logger.info(
                f"SKIP {market.slug}: edge too small - {tape_direction} | "
                f"BTC ${price.price:,.2f} vs ${strike:,.2f} | "
                f"our p={confidence:.3f} vs mkt={take_price:.3f} | "
                f"edge={edge:.3f} < {config.MIN_EDGE_THRESHOLD}"
            )
            return None

        # Confidence tier for position sizing
        if edge >= 0.20:
            tier = "high"
        elif edge >= 0.12:
            tier = "medium"
        else:
            tier = "low"

        reasoning = (
            f"TAPE {tape_direction}: BTC ${price.price:,.2f} vs strike "
            f"${strike:,.2f} ({distance_pct*100:+.3f}%) | "
            f"{seconds_left:.0f}s left | "
            f"our p={confidence:.1%} vs mkt={take_price:.1%} | "
            f"edge={edge:.1%} ({tier}) | "
            f"mom={momentum.crossover} rsi={momentum.rsi:.0f}"
        )

        logger.info(f"SIGNAL: {tape_direction} | {reasoning}")

        return Signal(
            direction=tape_direction,
            confidence=confidence,
            market_prob=take_price,
            edge=edge,
            bet_token_id=bet_token,
            bet_size_hint=tier,
            reasoning=reasoning,
        )

    def _tape_confidence(
        self,
        distance_pct: float,
        seconds_left: float,
        momentum: MomentumData,
        tape_direction: str,
    ) -> float:
        """
        Estimate the probability that BTC stays on the tape-favoured
        side of strike until the window closes.

        Three ingredients:
          1. Distance: further from strike = harder to reverse.
          2. Time: less time remaining = harder to reverse.
          3. Momentum: aligned momentum boosts, opposing momentum shaves.
        """
        # (1) Distance x time, fed into a sigmoid. Steepness grows as
        # the window closes, so 30s left with a $50 lead is near-certain.
        abs_dist = abs(distance_pct)

        # Time factor: at t=60s factor~1.0; at t=10s factor~6.0.
        time_factor = max(1.0, 60.0 / max(seconds_left, 1.0))

        # k calibrated so at t=30s a ~0.04% lead gives ~0.60, 0.1% ~0.75,
        # 0.2% ~0.90. We already branched on sign of distance, so base>=0.5.
        k = 8000.0 * time_factor
        base = 1.0 / (1.0 + math.exp(-k * abs_dist))

        # (2) Momentum alignment: does short-term momentum support the tape?
        aligned = self._momentum_alignment(momentum, tape_direction)
        # aligned in [-1, +1]. Shift base by up to +/- 0.08.
        base = base + 0.08 * aligned

        # (3) Volatility dampening: very choppy tape -> pull toward 0.5.
        vol = momentum.volatility
        vol_damp = max(0.6, 1.0 - vol * 40.0)
        base = 0.5 + (base - 0.5) * vol_damp

        return max(0.50, min(0.98, base))

    def _momentum_alignment(
        self, momentum: MomentumData, tape_direction: str
    ) -> float:
        """
        Return a value in [-1, +1] measuring how well short-term
        momentum agrees with the tape direction.
        """
        # Positive score = bullish, negative = bearish.
        score = 0.0

        if momentum.crossover == "bullish":
            score += 0.4
        elif momentum.crossover == "bearish":
            score -= 0.4

        # RSI: only the extremes matter for a 5-min window.
        if momentum.rsi > 65:
            score += 0.2
        elif momentum.rsi < 35:
            score -= 0.2

        # 5-minute momentum (how much BTC moved over the last 5 min)
        mom5 = momentum.momentum_5m
        if mom5 > 0.0005:
            score += min(0.4, mom5 * 200)
        elif mom5 < -0.0005:
            score += max(-0.4, mom5 * 200)

        score = max(-1.0, min(1.0, score))

        # If tape is NO (BTC below strike), a bearish score HELPS us,
        # so flip the sign to align with the tape direction.
        if tape_direction == "NO":
            score = -score

        return score
