import logging
import math
from dataclasses import dataclass
from typing import Optional

import config
from market_scanner import MarketInfo
from price_feed import PriceSnapshot, MomentumData

logger = logging.getLogger("polymarket_bot.strategy")


@dataclass
class Signal:
    """A trading signal generated by the strategy."""
    direction: str        # "YES" or "NO"
    confidence: float     # Our estimated probability (0-1)
    market_prob: float    # Market-implied probability
    edge: float           # confidence - market_prob (for YES direction)
    bet_token_id: str     # Token ID to buy
    bet_size_hint: str    # "low", "medium", "high" confidence tier
    reasoning: str        # Human-readable explanation


class TradingStrategy:
    """
    Generates trading signals for BTC 5-minute binary markets.

    Core insight: Late in a 5-minute window, the current BTC price relative
    to the strike price is highly predictive of the outcome. The strategy
    looks for cases where Polymarket prices lag behind reality.
    """

    # Weights for probability factors
    WEIGHT_DISTANCE = 0.50
    WEIGHT_MOMENTUM = 0.30
    WEIGHT_VOLATILITY = 0.20

    def analyze(
        self,
        market: MarketInfo,
        price: PriceSnapshot,
        momentum: MomentumData,
        yes_price: float,
        no_price: float,
    ) -> Optional[Signal]:
        """
        Analyze a market and return a Signal if edge is detected.

        Returns None if no tradeable edge exists.
        """
        seconds_left = market.seconds_until_close
        strike = market.strike_price

        # Don't trade if too early or too late
        if seconds_left > config.ENTRY_SECONDS_BEFORE_CLOSE:
            return None
        if seconds_left < config.LATEST_ENTRY_SECONDS:
            logger.debug(f"Too late to enter ({seconds_left:.0f}s left).")
            return None

        # Don't trade if strike price couldn't be parsed
        if strike <= 0:
            logger.warning(f"Invalid strike price for market: {market.question}")
            return None

        # Don't trade if market prices look stale
        if yes_price <= 0.02 or yes_price >= 0.98:
            logger.debug("Market prices look stale, skipping.")
            return None

        # Step 1: Estimate our probability that BTC finishes above strike
        our_up_prob = self._estimate_up_probability(
            current_price=price.price,
            strike_price=strike,
            momentum=momentum,
            seconds_remaining=seconds_left,
        )

        # Step 2: Get market-implied probability
        market_up_prob = yes_price  # YES price = implied probability of UP
        market_down_prob = no_price

        # Step 3: Calculate edge for both directions
        yes_edge = our_up_prob - market_up_prob
        no_edge = (1 - our_up_prob) - market_down_prob

        # Step 4: Pick the best direction
        if yes_edge >= config.MIN_EDGE_THRESHOLD and yes_edge >= no_edge:
            direction = "YES"
            edge = yes_edge
            confidence = our_up_prob
            bet_token = market.yes_token_id
        elif no_edge >= config.MIN_EDGE_THRESHOLD and no_edge > yes_edge:
            direction = "NO"
            edge = no_edge
            confidence = 1 - our_up_prob
            bet_token = market.no_token_id
        else:
            logger.debug(
                f"No edge detected. Our UP prob: {our_up_prob:.3f}, "
                f"Market: {market_up_prob:.3f}, "
                f"YES edge: {yes_edge:.3f}, NO edge: {no_edge:.3f}"
            )
            return None

        # Step 5: Determine confidence tier
        if edge >= 0.25:
            tier = "high"
        elif edge >= 0.15:
            tier = "medium"
        else:
            tier = "low"

        reasoning = (
            f"BTC ${price.price:,.2f} vs strike ${strike:,.2f} | "
            f"{seconds_left:.0f}s left | "
            f"Our prob: {confidence:.1%} vs Market: {market_up_prob:.1%} | "
            f"Edge: {edge:.1%} ({tier}) | "
            f"Momentum: {momentum.crossover}, RSI: {momentum.rsi:.1f}"
        )

        logger.info(f"SIGNAL: {direction} | {reasoning}")

        return Signal(
            direction=direction,
            confidence=confidence,
            market_prob=market_up_prob if direction == "YES" else market_down_prob,
            edge=edge,
            bet_token_id=bet_token,
            bet_size_hint=tier,
            reasoning=reasoning,
        )

    def _estimate_up_probability(
        self,
        current_price: float,
        strike_price: float,
        momentum: MomentumData,
        seconds_remaining: float,
    ) -> float:
        """
        Estimate the probability that BTC will be above strike at expiry.

        Combines three factors:
        1. Price distance (how far current price is from strike)
        2. Momentum (short-term trend direction and strength)
        3. Volatility (recent price variance)
        """
        # Factor 1: Price Distance (sigmoid model)
        distance_pct = (current_price - strike_price) / strike_price

        # Sigmoid steepness increases as time remaining decreases
        # (less time = current price more predictive)
        time_factor = max(1.0, 300.0 / max(seconds_remaining, 1.0))
        k = 500.0 * time_factor  # Base steepness * time factor

        distance_prob = 1.0 / (1.0 + math.exp(-k * distance_pct))

        # Factor 2: Momentum
        momentum_score = self._compute_momentum_score(momentum)
        momentum_prob = 0.5 + (momentum_score * 0.15)
        momentum_prob = max(0.05, min(0.95, momentum_prob))

        # Factor 3: Volatility adjustment
        # High volatility = less confidence in any direction (shrink toward 0.5)
        vol_scaling = 50.0  # Tunable: how much volatility affects confidence
        vol_dampening = max(0.3, 1.0 - momentum.volatility * vol_scaling)

        # Adjust distance probability by volatility
        vol_adjusted_prob = 0.5 + (distance_prob - 0.5) * vol_dampening

        # Weighted combination
        combined = (
            self.WEIGHT_DISTANCE * distance_prob
            + self.WEIGHT_MOMENTUM * momentum_prob
            + self.WEIGHT_VOLATILITY * vol_adjusted_prob
        )

        # Clamp to valid probability range
        return max(0.02, min(0.98, combined))

    def _compute_momentum_score(self, momentum: MomentumData) -> float:
        """
        Compute a momentum score from -1 (strong bearish) to +1 (strong bullish).

        Factors:
        - EMA crossover direction
        - RSI (overbought/oversold)
        - 5-minute price momentum
        - Price position relative to fast EMA
        """
        score = 0.0

        # EMA crossover (+/- 0.3)
        if momentum.crossover == "bullish":
            score += 0.3
        elif momentum.crossover == "bearish":
            score -= 0.3

        # RSI signal (+/- 0.2)
        if momentum.rsi > 70:
            score -= 0.1  # Overbought, potential reversal
        elif momentum.rsi < 30:
            score += 0.1  # Oversold, potential bounce
        elif momentum.rsi > 55:
            score += 0.1  # Mild bullish
        elif momentum.rsi < 45:
            score -= 0.1  # Mild bearish

        # 5-minute momentum (+/- 0.3)
        mom_5m = momentum.momentum_5m
        if mom_5m > 0.001:  # > 0.1% up in 5 min
            score += min(0.3, mom_5m * 100)
        elif mom_5m < -0.001:
            score += max(-0.3, mom_5m * 100)

        # Price vs EMA (+/- 0.2)
        pve = momentum.price_vs_ema
        if pve > 0:
            score += min(0.2, pve * 50)
        else:
            score += max(-0.2, pve * 50)

        return max(-1.0, min(1.0, score))
