-- Durable Postgres schema for the Polymarket Edge engine.
-- Tables are backend-owned; RLS is enabled for Supabase Data API defense in depth.

create table if not exists public.events (
  id integer generated by default as identity primary key,
  event_id varchar(128) not null,
  slug varchar(512),
  title text,
  category varchar(255),
  active boolean not null default true,
  closed boolean not null default false,
  end_date timestamptz,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ix_events_event_id on public.events (event_id);

create table if not exists public.markets (
  id integer generated by default as identity primary key,
  market_id varchar(128) not null,
  event_id varchar(128),
  condition_id varchar(256),
  slug varchar(512),
  question text,
  active boolean not null default true,
  closed boolean not null default false,
  volume double precision not null default 0,
  liquidity double precision not null default 0,
  end_date timestamptz,
  resolution_rules text,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ix_markets_market_id on public.markets (market_id);
create index if not exists ix_markets_event_id on public.markets (event_id);
create index if not exists ix_markets_condition_id on public.markets (condition_id);

create table if not exists public.tokens (
  id integer generated by default as identity primary key,
  token_id varchar(256) not null,
  market_id varchar(128) not null references public.markets (market_id),
  condition_id varchar(256),
  outcome varchar(512),
  outcome_index integer,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ix_tokens_token_id on public.tokens (token_id);
create index if not exists ix_tokens_market_id on public.tokens (market_id);
create index if not exists ix_tokens_condition_id on public.tokens (condition_id);

create table if not exists public.orderbook_snapshots (
  id integer generated by default as identity primary key,
  token_id varchar(256) not null references public.tokens (token_id),
  timestamp timestamptz not null default now(),
  best_bid double precision,
  best_ask double precision,
  mid double precision,
  spread double precision,
  bid_depth jsonb not null default '[]'::jsonb,
  ask_depth jsonb not null default '[]'::jsonb,
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_orderbook_snapshots_token_id on public.orderbook_snapshots (token_id);
create index if not exists ix_orderbook_snapshots_timestamp on public.orderbook_snapshots (timestamp);
create index if not exists ix_orderbook_snapshots_token_timestamp
  on public.orderbook_snapshots (token_id, timestamp desc);

create table if not exists public.trades (
  id integer generated by default as identity primary key,
  timestamp timestamptz,
  token_id varchar(256),
  condition_id varchar(256),
  market_slug varchar(512),
  outcome varchar(512),
  side varchar(16),
  price double precision,
  size double precision,
  proxy_wallet varchar(256),
  tx_hash varchar(256),
  raw_json jsonb not null default '{}'::jsonb,
  constraint uq_trades_tx_hash unique (tx_hash)
);

create index if not exists ix_trades_timestamp on public.trades (timestamp);
create index if not exists ix_trades_token_id on public.trades (token_id);
create index if not exists ix_trades_condition_id on public.trades (condition_id);

create table if not exists public.edge_snapshots (
  id integer generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  market_id varchar(128),
  token_id varchar(256) not null,
  side varchar(16),
  p_hat double precision,
  sigma_p double precision,
  bid double precision,
  ask double precision,
  raw_edge double precision,
  total_cost double precision,
  net_edge double precision,
  kelly_size double precision,
  action varchar(16) not null default 'NONE',
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_edge_snapshots_timestamp on public.edge_snapshots (timestamp);
create index if not exists ix_edge_snapshots_market_id on public.edge_snapshots (market_id);
create index if not exists ix_edge_snapshots_token_id on public.edge_snapshots (token_id);
create index if not exists ix_edge_snapshots_action on public.edge_snapshots (action);
create index if not exists ix_edge_snapshots_action_net_edge
  on public.edge_snapshots (action, net_edge desc);

create table if not exists public.paper_orders (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  market_id varchar(128),
  token_id varchar(256) not null,
  side varchar(16) not null,
  limit_price double precision not null,
  size double precision not null,
  edge_score double precision,
  status varchar(32) not null default 'created',
  simulated_fill_price double precision,
  simulated_pnl double precision,
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_paper_orders_market_id on public.paper_orders (market_id);
create index if not exists ix_paper_orders_token_id on public.paper_orders (token_id);
create index if not exists ix_paper_orders_created_at on public.paper_orders (created_at desc);

create table if not exists public.paper_positions (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  market_id varchar(128),
  token_id varchar(256) not null,
  shares double precision not null default 0,
  avg_price double precision not null default 0,
  cost_basis double precision not null default 0,
  realised_pnl double precision not null default 0,
  raw_json jsonb not null default '{}'::jsonb
);

create unique index if not exists ix_paper_positions_token_id on public.paper_positions (token_id);
create index if not exists ix_paper_positions_market_id on public.paper_positions (market_id);

create table if not exists public.live_orders (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  client_order_id varchar(256),
  exchange_order_id varchar(256),
  market_id varchar(128),
  token_id varchar(256),
  side varchar(16),
  price double precision,
  size double precision,
  notional double precision,
  status varchar(32) not null default 'created',
  edge_snapshot_id integer references public.edge_snapshots (id),
  risk_snapshot_json jsonb not null default '{}'::jsonb,
  raw_request_json jsonb not null default '{}'::jsonb,
  raw_response_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_live_orders_client_order_id on public.live_orders (client_order_id);
create index if not exists ix_live_orders_exchange_order_id on public.live_orders (exchange_order_id);
create index if not exists ix_live_orders_market_id on public.live_orders (market_id);
create index if not exists ix_live_orders_token_id on public.live_orders (token_id);
create index if not exists ix_live_orders_edge_snapshot_id on public.live_orders (edge_snapshot_id);

create table if not exists public.live_fills (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_id integer references public.live_orders (id),
  exchange_trade_id varchar(256),
  price double precision,
  size double precision,
  fee double precision,
  tx_hash varchar(256),
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_live_fills_order_id on public.live_fills (order_id);

create table if not exists public.risk_events (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  severity varchar(32) not null default 'warning',
  event_type varchar(128) not null,
  message text not null,
  raw_json jsonb not null default '{}'::jsonb
);

create table if not exists public.account_snapshots (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  cash_balance double precision,
  open_exposure double precision,
  realised_pnl double precision,
  unrealised_pnl double precision,
  raw_json jsonb not null default '{}'::jsonb
);

create table if not exists public.kill_switch_events (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  reason text not null,
  raw_json jsonb not null default '{}'::jsonb
);

create table if not exists public.news_items (
  id integer generated by default as identity primary key,
  dedup_hash varchar(64) not null,
  source varchar(32) not null,
  source_name varchar(255),
  url text,
  title text not null,
  summary text,
  language varchar(16),
  published_at timestamptz,
  fetched_at timestamptz not null default now(),
  entities jsonb not null default '[]'::jsonb,
  raw_json jsonb not null default '{}'::jsonb
);

create unique index if not exists ix_news_items_dedup_hash on public.news_items (dedup_hash);
create index if not exists ix_news_items_source on public.news_items (source);
create index if not exists ix_news_items_published_at on public.news_items (published_at);
create index if not exists ix_news_items_fetched_at on public.news_items (fetched_at);

create table if not exists public.news_signals (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  news_id integer not null references public.news_items (id),
  market_id varchar(128),
  token_id varchar(256),
  relevance double precision not null default 0,
  direction varchar(16) not null default 'NONE',
  confidence double precision not null default 0,
  implied_p double precision,
  model varchar(64) not null default 'deterministic',
  rationale text,
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_news_signals_created_at on public.news_signals (created_at);
create index if not exists ix_news_signals_news_id on public.news_signals (news_id);
create index if not exists ix_news_signals_market_id on public.news_signals (market_id);
create index if not exists ix_news_signals_token_id on public.news_signals (token_id);

alter table public.events enable row level security;
alter table public.markets enable row level security;
alter table public.tokens enable row level security;
alter table public.orderbook_snapshots enable row level security;
alter table public.trades enable row level security;
alter table public.edge_snapshots enable row level security;
alter table public.paper_orders enable row level security;
alter table public.paper_positions enable row level security;
alter table public.live_orders enable row level security;
alter table public.live_fills enable row level security;
alter table public.risk_events enable row level security;
alter table public.account_snapshots enable row level security;
alter table public.kill_switch_events enable row level security;
alter table public.news_items enable row level security;
alter table public.news_signals enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
