-- News ingestion + signal tables for the live breaking-news edge pipeline.

create table if not exists public.news_items (
  id integer generated by default as identity primary key,
  dedup_hash varchar(64) not null,
  source varchar(32) not null,
  source_name varchar(255),
  url text,
  title text not null,
  summary text,
  language varchar(16),
  published_at timestamptz,
  fetched_at timestamptz not null default now(),
  entities jsonb not null default '[]'::jsonb,
  raw_json jsonb not null default '{}'::jsonb
);

create unique index if not exists ix_news_items_dedup_hash on public.news_items (dedup_hash);
create index if not exists ix_news_items_source on public.news_items (source);
create index if not exists ix_news_items_published_at on public.news_items (published_at);
create index if not exists ix_news_items_fetched_at on public.news_items (fetched_at);

create table if not exists public.news_signals (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  news_id integer not null references public.news_items (id),
  market_id varchar(128),
  token_id varchar(256),
  relevance double precision not null default 0,
  direction varchar(16) not null default 'NONE',
  confidence double precision not null default 0,
  implied_p double precision,
  model varchar(64) not null default 'deterministic',
  rationale text,
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists ix_news_signals_created_at on public.news_signals (created_at);
create index if not exists ix_news_signals_news_id on public.news_signals (news_id);
create index if not exists ix_news_signals_market_id on public.news_signals (market_id);
create index if not exists ix_news_signals_token_id on public.news_signals (token_id);

alter table public.news_items enable row level security;
alter table public.news_signals enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
