-- Paper wallet positions for the $1000 live-data simulator.

create table if not exists public.paper_positions (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  market_id varchar(128),
  token_id varchar(256) not null,
  shares double precision not null default 0,
  avg_price double precision not null default 0,
  cost_basis double precision not null default 0,
  realised_pnl double precision not null default 0,
  raw_json jsonb not null default '{}'::jsonb
);

create unique index if not exists ix_paper_positions_token_id on public.paper_positions (token_id);
create index if not exists ix_paper_positions_market_id on public.paper_positions (market_id);

alter table public.paper_positions enable row level security;

revoke all on public.paper_positions from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
